name: bededa
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.7.2
  - argparse=1.4.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2021.5.30
  - colorama=0.4.5
  - cycler=0.11.0
  - dbus=1.13.6
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.78.3
  - glib-tools=2.78.3
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - icu=69.1
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.3.1
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=13.0.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgomp=13.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm13=13.0.1
  - libnsl=2.0.1
  - libogg=1.3.4
  - libopenblas=0.3.25
  - libopus=1.3.1
  - libpng=1.6.42
  - libpq=14.5
  - libsqlite=3.45.1
  - libstdcxx-ng=13.2.0
  - libtiff=4.3.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzlib=1.2.13
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - ncurses=6.4
  - nspr=4.35
  - nss=3.97
  - numpy=1.19.5
  - olefile=0.46
  - openjpeg=2.5.0
  - openssl=1.1.1w
  - pandas=1.1.5
  - patsy=0.5.6
  - pcre2=10.42
  - pillow=8.3.2
  - pip=21.3.1
  - pthread-stubs=0.4
  - pyparsing=3.1.1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - python=3.6.15
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytz=2023.3.post1
  - qt=5.12.9
  - readline=8.2
  - scipy=1.5.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.45.1
  - statsmodels=0.12.2
  - tk=8.6.13
  - tornado=6.1
  - tqdm=4.65.0
  - wheel=0.37.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.5
